from crewai import Agent
from textwrap import dedent
from langchain_openai import ChatOpenAI

from langchain_community.tools.wikidata.tool import WikidataAPIWrapper, WikidataQueryRun

from langchain.tools import WikipediaQueryRun
from langchain_community.utilities import WikipediaAPIWrapper
from langchain_community.tools import DuckDuckGoSearchRun

wikipedia = WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())

wikidata = WikidataQueryRun(api_wrapper=WikidataAPIWrapper())

search_tool = DuckDuckGoSearchRun()

class AssignmentHelperAgents:
    def __init__(self):
        self.OpenAIGPT41106 = ChatOpenAI(model_name="gpt-4-1106-preview	", temperature=0.3)
        self.OpenAIGPT40125 = ChatOpenAI(model_name="gpt-4-0125-preview", temperature=0.3)
        self.OpenAIGPT3Turbo= ChatOpenAI(model_name="gpt-3.5-turbo-0125", temperature=0.3)

    def IdeaGeneratorAgent(self):
        return Agent(
            role="Report Idea Generator",
            backstory=dedent("""
               You help students with their research. Lets say a student wants to write a report on famous Canadians. 
               In this case you will search and generate ideas to explore. You will not write the report, but generate ideas
            """),
            goal=dedent("""
                Use the tools you have to search and generate ideas for the user.
            """),
            allow_delegation=False,
            verbose=True,
            llm=self.OpenAIGPT40125,
            tools=[search_tool, wikipedia, wikidata]
        )

    def ReportWriterAgent(self):
        return Agent(
            role="Report Writer",
            backstory=dedent("""
                You help students with writing reports for their projects. 
                You get the ideas from the Idea Generator and then use the tools you have to write the report. 
                If feedback is give to you on your report, then you will revise your report
            """),
            goal=dedent("""
                You help write the report based on the ideas generated by the Idea Generator. You will structure the report based on direction by the user.
                A report should have these sections: Introduction, Body, Conclusion.
                You will use the Search, Wikipedia and Wikidata tools you have to collect data to write the report. If feedback is given to you then you will use the feedback to revise the report
            """),
            allow_delegation=False,
            verbose=True,
            llm=self.OpenAIGPT40125,
            tools=[search_tool, wikipedia, wikidata]
        )

    def ReportEvaluatorAgent(self):
        return Agent(
            role="Report Evaluator",
            backstory=dedent("""\
                You look through the written report and identify any opportunities for improvement
                """),
            goal=dedent("""\
                You review the written report and check it against the rubric - 
                1. Does it meets the user criteria, 2. Is it coherent. 3. Is it the appropriate length. 4. Does it has an intro, body and conclusion, 5. Is it interesting, 6. Is it accurate
                You can use the tools you have to check the accuracy of the report
                . Based on your observation you provide opportunities for improvement or a pass
            """),
            allow_delegation=True,
            llm=self.OpenAIGPT40125,
            verbose=True,
            tools=[search_tool, wikidata, wikipedia]
        )

    